"""Natural-language and scaffold helpers for teammates."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from cap_qa_platform.paths import EXPECTATIONS_DIR, PACKAGE_ROOT

TEMPLATE_SCENARIO = '''"""Auto-scaffolded RPC scenario for {scenario_id}."""
from __future__ import annotations

from cap_qa_platform.rpc.client import OdooRPCClient
from cap_qa_platform.scenarios.base import ScenarioRunResult, StepOutcome


class {class_name}:
    SCENARIO_ID = "{scenario_id}"

    def __init__(self, no_cleanup: bool = False, **kwargs):
        self.no_cleanup = no_cleanup

    def bind_admin(self, admin) -> None:
        self.admin = admin

    def run(self, rpc: OdooRPCClient, role_name: str) -> ScenarioRunResult:
        result = ScenarioRunResult(scenario=self.SCENARIO_ID, role_name=role_name, success=False)
        try:
            # TODO: {brief}
            result.success = True
        except Exception as exc:
            result.failed_step = "script"
            result.error = str(exc)
        return result

    def cleanup_as_admin(self, admin) -> None:
        pass
'''

TEMPLATE_EXPECTATIONS = {
    "scenario": "",
    "description": "",
    "modules": [],
    "full_access": ["President"],
    "blocked": {},
    "notes": "Generated by cap_qa_platform scaffold — review after first matrix run.",
}


def parse_natural_command(text: str) -> dict:
    """Parse simple teammate prompts into structured commands."""
    t = text.strip().lower()
    out: dict = {"raw": text}

    if re.search(r"\blist\b", t):
        out["action"] = "list"
    elif re.search(r"\bscaffold\b|\badd\b|\bcreate\b", t):
        out["action"] = "scaffold"
    elif re.search(r"\bfull\b|\bboth\b|\bui\b.*\bbackend\b|\bbackend\b.*\bui\b", t):
        out["action"] = "full"
    elif re.search(r"\bui\b", t):
        out["action"] = "ui"
    elif re.search(r"\bmatrix\b|\ball roles\b", t):
        out["action"] = "matrix"
    elif re.search(r"\bsmoke\b|\btest\b|\brun\b", t):
        out["action"] = "smoke"
    else:
        out["action"] = "smoke"

    for sid in (
        "so_cancel_old_customer",
        "so_link_project_invoice_color",
        "quality_issue_ask_for_review",
        "generate_task_test_ai",
        "task_need_solutions_ai",
        "quality_issue_approval",
        "inter_company_transaction",
        "hr_gamification_workflow",
        "ksc_auto_invoice",
        "connect_mistral_ai",
    ):
        if sid.replace("_", " ") in t or sid in t:
            out["scenario"] = sid
            break

    role_match = re.search(
        r"\b(president|ceo|team manager|sales manager|hr)\b",
        t,
        re.I,
    )
    if role_match:
        out["role"] = role_match.group(1).title()
        if out["role"].lower() == "hr":
            out["role"] = "HR"

  # scaffold name from "for my_feature" or "scenario foo_bar"
    m = re.search(r"(?:scenario|feature|module)\s+([a-z][a-z0-9_]+)", t)
    if m:
        out["new_scenario_id"] = m.group(1)

    brief_m = re.search(r"(?:that|to)\s+(.+)$", text.strip(), re.I)
    if brief_m:
        out["brief"] = brief_m.group(1).strip()

    return out


def scaffold_scenario(scenario_id: str, brief: str, modules: list[str] | None = None) -> dict:
    """Create scenario stub files under cap_qa_platform (does not edit test_automation)."""
    class_name = "".join(p.capitalize() for p in scenario_id.split("_")) + "Scenario"
    scenario_path = PACKAGE_ROOT / "scenarios" / f"{scenario_id}.py"
    if scenario_path.exists():
        raise FileExistsError(f"Scenario already exists: {scenario_path}")

    scenario_path.write_text(
        TEMPLATE_SCENARIO.format(
            scenario_id=scenario_id,
            class_name=class_name,
            brief=brief,
        ),
        encoding="utf-8",
    )

    exp = dict(TEMPLATE_EXPECTATIONS)
    exp["scenario"] = scenario_id
    exp["description"] = brief
    exp["modules"] = modules or []
    exp_path = EXPECTATIONS_DIR / f"{scenario_id}.json"
    exp_path.write_text(json.dumps(exp, indent=2) + "\n", encoding="utf-8")

    registry_path = PACKAGE_ROOT / "scenarios" / "registry.py"
    reg_text = registry_path.read_text(encoding="utf-8")
    import_line = f"from cap_qa_platform.scenarios.{scenario_id} import {class_name}\n"
    if import_line not in reg_text:
        anchor = "from cap_qa_platform.scenarios."
        pos = reg_text.find(anchor)
        if pos == -1:
            raise ValueError(f"Cannot patch registry.py: no import anchor found in {registry_path}")
        reg_text = reg_text[:pos] + import_line + reg_text[pos:]
    entry = f'    "{scenario_id}": {class_name},\n'
    if f'"{scenario_id}":' not in reg_text:
        reg_text = reg_text.replace(
            "SCENARIO_CLASSES: dict[str, type] = {",
            "SCENARIO_CLASSES: dict[str, type] = {\n" + entry,
        )
    registry_path.write_text(reg_text, encoding="utf-8")

    return {
        "scenario": scenario_id,
        "scenario_file": str(scenario_path),
        "expectations_file": str(exp_path),
        "next_steps": [
            f"Implement steps in {scenario_path.name}",
            f"Register in catalog.py ROLE_MATRIX_ENTRIES or SCRIPT_ENTRIES",
            f"python3 run_qa.py ask 'run smoke {scenario_id} President'",
        ],
    }


def print_ask_help() -> None:
    print(
        """Natural language examples (cap_qa_platform):

  run smoke so_cancel_old_customer for President
  test matrix so_cancel_old_customer all roles
  run ui so_cancel_old_customer
  run full so_cancel_old_customer President
  list scenarios
  scaffold scenario my_new_feature that confirms invoice and checks total

Use: python3 run_qa.py ask "<your prompt>"
"""
    )
