"""Generate RPC smoke tests and register catalog entries from module analysis."""
from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path

from cap_qa_platform.discovery.module_analyzer import analyze_module
from cap_qa_platform.paths import ADDONS_ROOT, EXPECTATIONS_DIR, PACKAGE_ROOT


def _pick_api_key_field(config_fields: dict[str, str]) -> tuple[str, str]:
    for name, param in config_fields.items():
        if "api_key" in name or name.endswith("_key"):
            return name, param
    for name in config_fields:
        if name.endswith("_key_enabled"):
            prefix = name.replace("_key_enabled", "")
            return config_fields.get(f"{prefix}_api_key", f"{prefix}_key"), config_fields.get(f"{prefix}_api_key", "")
    return "api_key", ""


def _pick_enabled_field(config_fields: dict[str, str], api_field: str) -> str | None:
    if api_field.endswith("_api_key"):
        candidate = api_field.replace("_api_key", "_key_enabled")
        if candidate in config_fields:
            return candidate
    prefix = api_field.replace("_key", "")
    candidate = f"{prefix}_key_enabled"
    return candidate if candidate in config_fields else None


def _render_ai_connector_rpc_test(analysis: dict) -> str:
    module = analysis["technical_name"]
    ai = analysis["ai_connector"]
    llm_models = ai["llm_models"] or ["model-placeholder"]
    default_llm = ai["default_llm"] or llm_models[0]
    param_key = ai["param_api_key"] or f"{module}.api_key"
    config_fields = ai["config_fields"]
    api_field, _ = _pick_api_key_field(config_fields)
    enabled_field = _pick_enabled_field(config_fields, api_field)
    depends = tuple(d for d in analysis["depends"] if d in ("ai", "ai_app")) or ("ai", "ai_app")

    settings_checks = [f'"{api_field}"']
    if enabled_field:
        settings_checks.append(f'"{enabled_field}"')

    llm_models_repr = ",\n    ".join(repr(m) for m in llm_models)
    depends_repr = ", ".join(repr(d) for d in depends)
    settings_fields_repr = ", ".join(settings_checks)

    return textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        # -*- coding: utf-8 -*-
        """Auto-generated structural RPC smoke test for {module}.

        Generated by cap_qa_platform discovery. Extend with live API tests as needed.

        Run:
            python3 models/test_{module}_rpc.py --url ... --db ... --user ... --password ...
        """
        from __future__ import annotations

        import argparse
        import json
        import sys
        import xmlrpc.client
        from typing import Any

        MODULE_NAME = {module!r}
        DEPENDENCY_MODULES = ({depends_repr})
        PARAM_API_KEY = {param_key!r}
        MODEL_CONFIG_SETTINGS = "res.config.settings"
        MODEL_AI_AGENT = "ai.agent"
        FIELD_AGENT_LLM_MODEL = "llm_model"
        LLM_MODELS = (
            {llm_models_repr}
        )
        DEFAULT_LLM = {default_llm!r}
        API_KEY_FIELD = {api_field!r}
        ENABLED_FIELD = {enabled_field!r}


        class OdooRPCClient:
            def __init__(self, url: str, db: str, username: str, password: str, protocol: str = "jsonrpc"):
                self.url = url.rstrip("/")
                self.db = db
                self.username = username
                self.password = password
                self.protocol = protocol.lower()
                self.uid: int | None = None
                self._json_id = 0

            def authenticate(self) -> int:
                if self.protocol == "xmlrpc":
                    common = xmlrpc.client.ServerProxy(f"{{self.url}}/xmlrpc/2/common", allow_none=True)
                    uid = common.authenticate(self.db, self.username, self.password, {{}})
                    if not uid:
                        raise RuntimeError("Authentication failed")
                    self.uid = uid
                    return uid
                uid = self._jsonrpc("common", "authenticate", [self.db, self.username, self.password, {{}}])
                if not uid:
                    raise RuntimeError("Authentication failed")
                self.uid = uid
                return uid

            def _jsonrpc(self, service: str, method: str, args: list) -> Any:
                import urllib.request

                self._json_id += 1
                payload = {{
                    "jsonrpc": "2.0",
                    "method": "call",
                    "params": {{"service": service, "method": method, "args": args}},
                    "id": self._json_id,
                }}
                req = urllib.request.Request(
                    f"{{self.url}}/jsonrpc",
                    data=json.dumps(payload).encode(),
                    headers={{"Content-Type": "application/json"}},
                )
                with urllib.request.urlopen(req, timeout=120) as resp:
                    data = json.loads(resp.read().decode())
                if data.get("error"):
                    raise RuntimeError(data["error"])
                return data.get("result")

            def execute_kw(self, model: str, method: str, args=None, kwargs=None) -> Any:
                args = args or []
                kwargs = kwargs or {{}}
                if self.protocol == "xmlrpc":
                    models = xmlrpc.client.ServerProxy(f"{{self.url}}/xmlrpc/2/object", allow_none=True)
                    return models.execute_kw(self.db, self.uid, self.password, model, method, args, kwargs)
                return self._jsonrpc(
                    "object",
                    "execute_kw",
                    [self.db, self.uid, self.password, model, method, args, kwargs],
                )

            def fields_get(self, model: str, field_names: list[str] | None = None) -> dict:
                return self.execute_kw(model, "fields_get", [field_names or []], {{"attributes": ["string", "type"]}})


        class ModuleSmokeTest:
            def __init__(self, client: OdooRPCClient):
                self.client = client
                self.failed = 0
                self.passed = 0
                self._agents: list[int] = []

            def _ok(self, label: str, ok: bool, detail: str = "") -> None:
                if ok:
                    self.passed += 1
                    print(f"  PASS  {{label}}")
                else:
                    self.failed += 1
                    suffix = f" — {{detail}}" if detail else ""
                    print(f"  FAIL  {{label}}{{suffix}}")

            def _module_installed(self, name: str) -> bool:
                ids = self.client.execute_kw("ir.module.module", "search", [[("name", "=", name), ("state", "=", "installed")]])
                return bool(ids)

            def _selection_keys(self, model: str, field: str) -> list[str]:
                meta = self.client.fields_get(model, [field]).get(field, {{}})
                selection = meta.get("selection") or []
                return [item[0] for item in selection]

            def run(self) -> bool:
                print("=" * 72)
                print(f"{{MODULE_NAME}} — structural RPC smoke")
                print("=" * 72)

                self._ok(f"Module {{MODULE_NAME!r}} installed", self._module_installed(MODULE_NAME))
                for dep in DEPENDENCY_MODULES:
                    self._ok(f"Dependency {{dep!r}} installed", self._module_installed(dep))

                llm_selection = self._selection_keys(MODEL_AI_AGENT, FIELD_AGENT_LLM_MODEL)
                for model_name in LLM_MODELS:
                    self._ok(
                        f"{{MODEL_AI_AGENT}}.{{FIELD_AGENT_LLM_MODEL}} includes {{model_name!r}}",
                        model_name in llm_selection,
                    )

                settings_fields = self.client.fields_get(MODEL_CONFIG_SETTINGS, [{settings_fields_repr}])
                self._ok(
                    f"{{MODEL_CONFIG_SETTINGS}}.{{API_KEY_FIELD}} exists",
                    API_KEY_FIELD in settings_fields,
                )
                if ENABLED_FIELD:
                    self._ok(
                        f"{{MODEL_CONFIG_SETTINGS}}.{{ENABLED_FIELD}} exists",
                        ENABLED_FIELD in settings_fields,
                    )

                agent_id = self.client.execute_kw(
                    MODEL_AI_AGENT,
                    "create",
                    [{{
                        "name": f"RPC Smoke {{MODULE_NAME}}",
                        "llm_model": DEFAULT_LLM,
                        "response_style": "balanced",
                    }}],
                )
                self._agents.append(agent_id)
                agent = self.client.execute_kw(
                    MODEL_AI_AGENT,
                    "read",
                    [[agent_id], [FIELD_AGENT_LLM_MODEL]],
                )[0]
                self._ok(
                    f"{{MODEL_AI_AGENT}} accepts provider LLM model",
                    agent[FIELD_AGENT_LLM_MODEL] == DEFAULT_LLM,
                    f"id={{agent_id}}",
                )

                print("=" * 72)
                print(f"Result: {{self.passed}} passed, {{self.failed}} failed")
                print("=" * 72)
                return self.failed == 0

            def cleanup(self) -> None:
                if self._agents:
                    try:
                        self.client.execute_kw(MODEL_AI_AGENT, "unlink", [self._agents])
                    except Exception:
                        pass


        def parse_args() -> argparse.Namespace:
            parser = argparse.ArgumentParser(description=f"RPC smoke test for {{MODULE_NAME}}")
            parser.add_argument("--url", default="http://localhost:8069")
            parser.add_argument("--db", default="odoo")
            parser.add_argument("--user", default="admin")
            parser.add_argument("--password", default="admin")
            parser.add_argument("--protocol", choices=["jsonrpc", "xmlrpc"], default="jsonrpc")
            return parser.parse_args()


        def main() -> int:
            args = parse_args()
            client = OdooRPCClient(args.url, args.db, args.user, args.password, args.protocol)
            client.authenticate()
            tester = ModuleSmokeTest(client)
            try:
                ok = tester.run()
            finally:
                tester.cleanup()
            return 0 if ok else 1


        if __name__ == "__main__":
            sys.exit(main())
        '''
    )


def _render_generic_rpc_test(analysis: dict) -> str:
    module = analysis["technical_name"]
    depends = analysis["depends"][:5]
    depends_repr = ", ".join(repr(d) for d in depends) if depends else ""

    return textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        # -*- coding: utf-8 -*-
        """Auto-generated generic RPC smoke test for {module}."""
        from __future__ import annotations

        import argparse
        import json
        import sys
        import urllib.request

        MODULE_NAME = {module!r}
        DEPENDENCY_MODULES = ({depends_repr})


        def rpc_execute(url, db, uid, password, model, method, args=None, kwargs=None):
            payload = {{
                "jsonrpc": "2.0",
                "method": "call",
                "params": {{
                    "service": "object",
                    "method": "execute_kw",
                    "args": [db, uid, password, model, method, args or [], kwargs or {{}}],
                }},
                "id": 1,
            }}
            req = urllib.request.Request(
                url.rstrip("/") + "/jsonrpc",
                data=json.dumps(payload).encode(),
                headers={{"Content-Type": "application/json"}},
            )
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.loads(resp.read().decode())
            if data.get("error"):
                raise RuntimeError(data["error"])
            return data.get("result")


        def auth(url, db, user, password):
            payload = {{
                "jsonrpc": "2.0",
                "method": "call",
                "params": {{"service": "common", "method": "authenticate", "args": [db, user, password, {{}}]}},
                "id": 1,
            }}
            req = urllib.request.Request(
                url.rstrip("/") + "/jsonrpc",
                data=json.dumps(payload).encode(),
                headers={{"Content-Type": "application/json"}},
            )
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.loads(resp.read().decode())
            uid = data.get("result")
            if not uid:
                raise RuntimeError("Authentication failed")
            return uid


        def installed(url, db, uid, password, name):
            ids = rpc_execute(url, db, uid, password, "ir.module.module", "search", [[("name", "=", name), ("state", "=", "installed")]])
            return bool(ids)


        def main() -> int:
            parser = argparse.ArgumentParser()
            parser.add_argument("--url", default="http://localhost:8069")
            parser.add_argument("--db", default="odoo")
            parser.add_argument("--user", default="admin")
            parser.add_argument("--password", default="admin")
            args = parser.parse_args()

            uid = auth(args.url, args.db, args.user, args.password)
            failed = 0
            if not installed(args.url, args.db, uid, args.password, MODULE_NAME):
                print(f"FAIL module {{MODULE_NAME}} not installed")
                failed += 1
            else:
                print(f"PASS module {{MODULE_NAME}} installed")
            for dep in DEPENDENCY_MODULES:
                if not installed(args.url, args.db, uid, args.password, dep):
                    print(f"FAIL dependency {{dep}} not installed")
                    failed += 1
                else:
                    print(f"PASS dependency {{dep}} installed")
            return 1 if failed else 0


        if __name__ == "__main__":
            sys.exit(main())
        '''
    )


def _register_catalog_entry(analysis: dict, script_relpath: str) -> None:
    catalog_path = PACKAGE_ROOT / "catalog.py"
    text = catalog_path.read_text(encoding="utf-8")
    module = analysis["technical_name"]
    if f'id="{module}"' in text:
        return

    description = re.sub(r"[\r\n\"']", " ", analysis.get("name") or module)[:120]
    dep_modules = [module]
    for dep in ("ai", "ai_app"):
        if dep in analysis["depends"] and dep not in dep_modules:
            dep_modules.append(dep)
    modules_tuple = ", ".join(repr(m) for m in dep_modules)

    entry = textwrap.dedent(
        f'''
    ScenarioEntry(
        id="{module}",
        kind="script",
        description="{description} (auto-generated smoke)",
        modules=({modules_tuple}),
        script_relpath="{script_relpath}",
        auth_user="admin",
        layers=("backend",),
    ),'''
    )

    anchor = '        script_relpath="connect_mistral_ai.py",\n        auth_user="admin",\n        layers=("backend",),\n    ),\n)'
    if anchor not in text:
        raise ValueError("Cannot patch catalog.py: SCRIPT_ENTRIES tail anchor missing")
    text = text.replace(anchor, anchor[:-2] + entry + "\n)", 1)
    catalog_path.write_text(text, encoding="utf-8")


def _write_expectations(analysis: dict) -> Path:
    module = analysis["technical_name"]
    exp = {
        "scenario": module,
        "description": f"{analysis['name']} auto-generated smoke",
        "modules": [analysis["technical_name"]],
        "full_access": ["President"],
        "blocked": {},
        "notes": "Generated by cap_qa_platform discovery — review after first run.",
    }
    exp_path = EXPECTATIONS_DIR / "scripts" / f"{module}.json"
    exp_path.parent.mkdir(parents=True, exist_ok=True)
    exp_path.write_text(json.dumps(exp, indent=2) + "\n", encoding="utf-8")
    return exp_path


def scaffold_module_test(module_name: str, *, register_catalog: bool = True, overwrite: bool = False) -> dict:
    analysis = analyze_module(module_name)
    module_dir = ADDONS_ROOT / module_name
    test_path = module_dir / "models" / f"test_{module_name}_rpc.py"

    if test_path.exists() and not overwrite:
        raise FileExistsError(f"RPC test already exists: {test_path} (pass overwrite=True)")

    if analysis["module_type"] == "ai_connector" and analysis["scaffold_ready"]:
        content = _render_ai_connector_rpc_test(analysis)
    else:
        content = _render_generic_rpc_test(analysis)

    test_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.write_text(content, encoding="utf-8")
    test_path.chmod(0o755)

    script_relpath = f"{module_name}/models/test_{module_name}_rpc.py"
    exp_path = _write_expectations(analysis)
    catalog_updated = False
    if register_catalog and module_name not in analysis["catalog_scenarios"]:
        _register_catalog_entry(analysis, script_relpath)
        catalog_updated = True

    return {
        "module": module_name,
        "module_type": analysis["module_type"],
        "test_file": str(test_path),
        "script_relpath": script_relpath,
        "expectations_file": str(exp_path),
        "catalog_updated": catalog_updated,
        "next_steps": [
            f"Review generated test: {test_path.name}",
            "Restart MCP server in Cursor if catalog was updated",
            f"python3 run_qa.py ask 'run smoke {module_name} for President'",
        ],
    }
