#!/usr/bin/env python3
import json, sys

# Load the JSON report generated by qa_odoo_full_test.py
with open('full_report_brune.json') as f:
    data = json.load(f)

for rec in data:
    tc = rec.get('tc')
    module = rec.get('module')
    action = rec.get('action')
    status = rec.get('status')
    detail = rec.get('detail')
    print(f"TC {tc}: {module} – {action} → {status}")
    if detail:
        print(f"    Detail: {detail}")
    print()
